# configs/v26/v26_m_seg_demo.yaml
base:
  - configs/_base_/datasets/coco_min_seg.yaml
  - configs/_base_/models/yolo26m_seg.yaml # <-- Lắp model Seg vào
  - configs/_base_/schedules/default_10e.yaml

train:
  epochs: 5
  batch: 4 # Seg tốn VRAM hơn nên có thể giảm batch size
  imgsz: 640
  name: "v26_m_seg_run"
  amp: False