# Danh sách các file cần gộp vào (Thứ tự quan trọng: file sau ghi đè file trước)
base:
  - configs/_base_/datasets/coco_min.yaml
  - configs/_base_/models/yolo11m.yaml
  - configs/_base_/schedules/default_10e.yaml

# Ghi đè tham số riêng cho lần chạy demo này
train:
  epochs: 5 # Demo chạy nhanh 5 epoch thôi
  batch: 8  # Máy yếu thì giảm batch size xuống
  name: "v11_m_demo_run" # Tên folder kết quả
  # THÊM DÒNG NÀY ĐỂ CHẶN DOWNLOAD
  amp: False