model:
  type: "YOLOv11Detector"
  weights_path: "models/hub/yolo11m.pt"
  imgsz: 640
  conf_threshold: 0.25

dataset:
  data_path: "data/raw/coco8.yaml" # File config data cá»§a ultralytics
  epochs: 10
  batch_size: 16